---
pre-commit:
  stage: test
  tags:
  - ffci
  image: 'ghcr.io/pre-commit-ci/runner-image@sha256:fe01a6ec51b298412990b88627c3973b1146c7304f930f469bafa29ba60bcde9'
  variables:
    XDG_CACHE_HOME: ".cache"
  script:
  - pre-commit run --all-files --show-diff-on-failure
  cache:
    key: pre-commit
    paths:
    - .cache
    when: 'always'
  needs: []

vagrant-validate:
  extends: .job
  stage: test
  tags: [ffci]
  variables:
    VAGRANT_VERSION: 2.3.7
  script:
  - ./tests/scripts/vagrant-validate.sh
  except: ['triggers', 'master']


# TODO: convert to pre-commit hook
check-galaxy-version:
  needs: []
  stage: test
  tags: [ffci]
  image: python:3
  script:
  - tests/scripts/check_galaxy_version.sh
